#docker exec -it learn_rxjs_mongo /bin/bash
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: learn_rxjs_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:27017
    #volumes:
      #- ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      #- ./mongodb:/data/db
 